---
# Staging inventory
all:
  vars:
    env: staging

  children:
    linux:
      children:
        webservers:
          hosts: {}
        dbservers:
          hosts: {}
        mgmt:
          hosts: {}

    windows:
      children:
        win_servers:
          hosts: {}
