#!/usr/bin/env python3
"""
tf_inventory.py — Convert Terraform outputs to an Ansible YAML inventory.

USAGE
-----
  # Generate from live Terraform state (requires 'terraform' on PATH):
  python3 scripts/tf_inventory.py --tf-dir /path/to/terraform/project

  # Generate from a pre-exported JSON file (GitHub Actions usage):
  python3 scripts/tf_inventory.py /tmp/tf_outputs.json

  # Print the inventory to stdout (redirect to file for -i flag):
  python3 scripts/tf_inventory.py --tf-dir ../infra > inventories/production/tf_hosts.yml

TERRAFORM OUTPUT CONTRACT
--------------------------
Your Terraform root module must expose an output named 'ansible_hosts' with
this structure (adjust the TF output block to match your resource names):

  output "ansible_hosts" {
    value = {
      linux = {
        webservers = {
          "web-01" = { ip = "10.0.1.10", extra_vars = {} }
          "web-02" = { ip = "10.0.1.11", extra_vars = { datadog_tags = ["role:web"] } }
        }
        dbservers = {
          "db-01" = { ip = "10.0.1.20", extra_vars = {} }
        }
      }
      windows = {
        win_servers = {
          "win-01" = { ip = "10.0.2.10", extra_vars = {} }
        }
      }
    }
  }
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

import yaml


def load_from_tf_dir(tf_dir: str) -> dict:
    """Run 'terraform output -json' and return parsed JSON."""
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=tf_dir,
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(result.stdout)


def load_from_file(path: str) -> dict:
    """Load Terraform outputs from a pre-exported JSON file."""
    with open(path) as f:
        return json.load(f)


def build_inventory(tf_outputs: dict) -> dict:
    """
    Transform Terraform outputs into an Ansible YAML inventory structure.

    Expected tf_outputs shape:
      { "ansible_hosts": { "value": { <os_family>: { <group>: { <hostname>: { ip, extra_vars } } } } } }
    """
    ansible_hosts = tf_outputs.get("ansible_hosts", {}).get("value", {})

    if not ansible_hosts:
        print(
            "WARNING: 'ansible_hosts' output not found or empty. "
            "Generating empty inventory.",
            file=sys.stderr,
        )

    inventory = {"all": {"children": {}}}

    for os_family, groups in ansible_hosts.items():
        # Top-level OS family group (linux, windows)
        family_entry: dict = {"children": {}}
        inventory["all"]["children"][os_family] = family_entry

        for group_name, hosts in groups.items():
            host_entries: dict = {}
            for hostname, attrs in hosts.items():
                host_vars = {"ansible_host": attrs["ip"]}
                host_vars.update(attrs.get("extra_vars", {}))
                host_entries[hostname] = host_vars

            family_entry["children"][group_name] = {"hosts": host_entries}

    return inventory


def main():
    parser = argparse.ArgumentParser(
        description="Generate Ansible inventory from Terraform outputs"
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--tf-dir",
        metavar="DIR",
        help="Path to Terraform working directory (runs 'terraform output -json')",
    )
    parser.add_argument(
        "json_file",
        nargs="?",
        metavar="FILE",
        help="Path to pre-exported Terraform outputs JSON file",
    )
    args = parser.parse_args()

    if args.tf_dir:
        tf_outputs = load_from_tf_dir(args.tf_dir)
    elif args.json_file:
        tf_outputs = load_from_file(args.json_file)
    else:
        parser.print_help()
        sys.exit(1)

    inventory = build_inventory(tf_outputs)

    print("---")
    print("# Generated by scripts/tf_inventory.py — do not edit manually")
    print(yaml.dump(inventory, default_flow_style=False, sort_keys=True))


if __name__ == "__main__":
    main()
