---
# Production inventory
all:
  vars:
    env: production

  children:
    linux:
      children:
        webservers:
          hosts: {}
        dbservers:
          hosts: {}
        mgmt:
          hosts: {}

    windows:
      children:
        win_servers:
          hosts: {}
